name: 'Docker tag from github.ref'
description: 'Generate Docker tag from github.ref'
author: 'Yuya Takeyama'
branding:
  icon: 'tag'
  color: 'blue'
inputs:
  latest-branches:
    required: false
    description: 'Comma-separated names of branches to be `latest` Docker tag'
    default: 'main,master'
  remove-version-tag-prefix:
    required: false
    description: 'Remove `v` from version tag prefix'
    default: 'true'
outputs:
  tag:
    description: 'Generated Docker tag'
runs:
  using: 'node12'
  main: 'dist/index.js'
